[build-dependencies]
serde = { workspace = true }
toml = { workspace = true }


[dependencies]
async-trait = { workspace = true }
config = { workspace = true }
dashmap = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
metrics = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-console = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true }
unbug = { workspace = true }
crossbeam-deque = { workspace = true }
num_cpus = { workspace = true }

[[example]]
name = "Sequence"
path = "Example/Sequence.rs"

[[example]]
name = "WorkSteal"
path = "Example/WorkSteal.rs"

[[example]]
name = "Tauri"
path = "Example/Tauri.rs"

[features]
Development = ["tokio-console"]
default = []

[lib]
crate-type = ["rlib"]
name = "Echo"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "Echo 📣"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "Echo"
publish = false
repository = "https://github.com/CodeEditorLand/Echo"
version = "0.0.1"
