[build-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.20" }

[dependencies]
async-trait = "0.1.88"
config = { version = "0.15.11" }
dashmap = { version = "6.1.0" }
env_logger = { version = "0.11.7" }
futures = { version = "0.3.31" }
log = { version = "0.4.27" }
metrics = { version = "0.24.1" }
rand = { version = "0.9.0" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
thiserror = { version = "2.0.12" }
tokio = { version = "1.44.1", features = ["full"] }
tokio-console = { version = "0.1.13", optional = true }
tokio-tungstenite = "0.26.2"
unbug = { version = "0.4.0" }

[[example]]
name = "Sequence"
path = "Example/Sequence.rs"

[[example]]
name = "WorkSteal"
path = "Example/WorkSteal.rs"

[[example]]
name = "Tauri"
path = "Example/Tauri.rs"

[features]
Development = ["tokio-console"]
default = []

[lib]
crate-type = ["rlib"]
name = "Echo"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "Echo 📣"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "Echo"
publish = false
repository = "https://github.com/CodeEditorLand/Echo"
version = "0.0.1"
